name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: qauinger
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with: 
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/qauinger/qauinger:latest
        platforms: linux/amd64,linux/arm64
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DO_QAUINGER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan 157.230.49.3 >> ~/.ssh/known_hosts
    - name: Docker pull and Restart
      run: |
        ssh root@157.230.49.3 '
          cd /docker/qauinger &&
          docker compose pull &&
          docker compose up -d
        '
